# Generated by Django 4.2.28 on 2026-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', help_text='Used for Food Miles calculation', max_length=20),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='business_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', help_text='Used for Food Miles calculation', max_length=20),
        ),
    ]
