# Generated by Django 4.2.29 on 2026-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customerorder_collection_type_order_collection_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='collection_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='collection_type',
            field=models.CharField(blank=True, help_text='The collection type for the order. Options are deliver to address or collect from producer.', max_length=50, null=True),
        ),
    ]
