# Generated by Django 4.2.29 on 2026-03-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_customerorder_collection_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='delivery_date',
        ),
    ]
