# Generated by Django 4.2.29 on 2026-03-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_customerorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount of the overall order including multi-vendor subtotals.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_order',
            field=models.ForeignKey(help_text='Parent customer order item this order belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.customerorder'),
        ),
    ]
