# Generated by Django 4.2.28 on 2026-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('DAIRY', 'Dairy'), ('BAKERY', 'Bakery'), ('PRESERVES', 'Preserves'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Is the product currently available?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('allergen_info', models.TextField(blank=True, help_text='List any allergens present in the product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
