# Generated by Django 4.2.28 on 2026-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergen_info',
            field=models.TextField(blank=True),
        ),
    ]
