# Generated by Django 4.2.28 on 2026-02-18 16:01


from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Product = apps.get_model('products', 'Product')
    
    # 1. Create Superuser (if not exists)
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@example.com',
            password=make_password('admin'),
            role='ADMIN',
            is_staff=True,
            is_superuser=True
        )

    # 2. Create Producer (if not exists)
    producer, created = User.objects.get_or_create(
        username='producer_bob',
        defaults={
            'email': 'bob@example.com',
            'role': 'PRODUCER',
            'password': make_password('producer123')
        }
    )
    if not created:
         producer.password = make_password('producer123')
         producer.save()


    # 3. Create Products
    # Products are seeded correctly using seed_db.py, skipping creation here to avoid string-to-int Category issues.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_allergen_info'),
        ('users', '0004_alter_user_groups_alter_user_user_permissions'), # Correct dependency name
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
