# Generated by Django 4.2.28 on 2026-02-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20260218_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vegetables, Dairy, Bakery, etc.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='best_before_date',
            field=models.DateField(blank=True, help_text='Required for customer transparency', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_organic',
            field=models.BooleanField(default=False, help_text='Supports customer quality filters'),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Automation for seasonal visibility (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Automation for seasonal visibility (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text="e.g., 'dozen', 'kg'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergen_info',
            field=models.TextField(blank=True, help_text='Compliance with food safety regulations', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Real-time inventory tracking'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
