# Generated by Django 4.2.28 on 2026-03-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text='List of major allergens from the UK 14 allergens list'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergen_info',
            field=models.TextField(blank=True, help_text='Additional allergen information not covered by the 14 major allergens', null=True),
        ),
    ]
