# Generated by Django 4.2.28 on 2026-03-25 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_recipe_farmstory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farmstory',
            unique_together={('producer', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('producer', 'title')},
        ),
    ]
