# Generated by Django 4.2.28 on 2026-03-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_is_deleted_product_allergens_and_more'),
        ('products', '0010_alter_farmstory_unique_together_and_more'),
    ]

    operations = [
    ]
