# Generated by Django 4.2.29 on 2026-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Notify producer when stock falls below this level'),
        ),
    ]
