# Generated by Django 4.2.28 on 2026-04-25 13:31

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[products.models.validate_product_image]),
        ),
    ]
