# Generated by Django 4.2.30 on 2026-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_seasonal_reminder_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seasonal_reminder_sent_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month (1-12) for which the last seasonal reminder was sent, to avoid duplicates', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seasonal_reminder_sent_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year for which the last seasonal reminder was sent, to avoid duplicates', null=True),
        ),
    ]
